"""add lead priority

Revision ID: 036460070218
Revises: fb4863110f37
Create Date: 2026-07-13 11:50:12.000338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036460070218'
down_revision: Union[str, Sequence[str], None] = 'fb4863110f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'leads',
    sa.Column(
        'priority',
        sa.Enum(
            'LOW',
            'MEDIUM',
            'HIGH',
            'URGENT',
            name='leadpriority'
        ),
        nullable=False,
        server_default='MEDIUM'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'priority')
    # ### end Alembic commands ###
