"""add next followup to leads

Revision ID: 8e81fa6f0f07
Revises: 036460070218
Create Date: 2026-07-13 22:06:28.257247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e81fa6f0f07'
down_revision: Union[str, Sequence[str], None] = '036460070218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('next_followup', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'next_followup')
    # ### end Alembic commands ###
